<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Le registre des clés d'idempotence.
 *
 * L'index unique n'est pas décoratif : c'est lui qui départage deux workers qui
 * consomment le même message au même instant, là où un SELECT suivi d'un INSERT
 * laisserait passer les deux.
 */
final class Version20260927104900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table handled_message et son index unique';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE handled_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, idempotency_key VARCHAR(255) NOT NULL, handled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_handled_message_idempotency_key ON handled_message (idempotency_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE handled_message');
    }
}
