<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La table du transport Doctrine de Messenger.
 *
 * Le DSN de l'application porte `auto_setup=0` : la table n'est donc pas créée
 * au premier `dispatch()`, comme le recommande la documentation de Symfony pour
 * la production. Le transport publie malgré tout son schéma, donc
 * `doctrine:migrations:diff` la voit et cette migration se génère comme
 * n'importe quelle autre. Le hook de post-build la joue à chaque déploiement.
 *
 * Une seule table pour les deux transports : `async` et `failed` partagent
 * `messenger_messages` et se séparent par la colonne `queue_name`.
 */
final class Version20260927104614 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table messenger_messages du transport Doctrine';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
    }
}
